sudo: required
services: 
    - docker
before_install:
    - docker build -t developercode38-art/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true developercode38-art/docker-react npm run test
